application: destiny-db
version: 1
runtime: python27
api_version: 1
default_expiration: 0
instance_class: F2
threadsafe: true

handlers:
- url: /_ah/warmup
  script: dashboard.user.app

- url: /(ezdemo[.]html)
  static_files: dashboard/\1
  upload: dashboard/ezdemo.html

- url: /(google38371e7df630b0a7[.]html)
  static_files: dashboard/\1
  upload: dashboard/google38371e7df630b0a7.html

- url: /(realtime[.]html)
  static_files: dashboard/\1
  upload: dashboard/realtime.html

- url: /(.*[.](css|ico|js|txt))
  static_files: dashboard/\1
  upload: .*[.](css|ico|js|txt)

- url: /(admin/?|admin/.*)
  secure: always
  login: admin
  script: dashboard.admin.app

- url: /(api/?|api/.*)
  secure: always
  script: dashboard.api.app

- url: /(ez/?|ez/.*)
  secure: always
  script: dashboard.ez.app

- url: /(db/?|db/.*)
  secure: always
  script: dashboard.db.app

- url: /.*
  secure: always
  script: dashboard.user.app

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
